### ISSUE TITLE
Torquebox 3

### ISSUE THREAD

**Issue by rwilliams** [torquebox/chef-cookbooks#6]
Could we get this updated for Torquebox 3?

**Comment by swistaczek** [comment]
+1 it would be great @bbrowning

**Comment by mthenw** [comment]
same here @bbrowning

**Comment by bbrowning** [comment]
It would be ideal if someone that uses Chef regularly could provide an update to this cookbook. I can take a stab at it if no one else wants to, but the only times I ever use Chef are when this cookbook needs updating.

**Comment by rabidpraxis** [comment]
I added a PR with updated XML config template for Torquebox 3 in https://github.com/torquebox/chef-cookbooks/pull/7

**Comment by r3bo0t** [comment]
@rabidpraxis, thanks for updating template corresponds to torquebox 3.  I have one question, does that work for you with the updates in the template file. I am getting error with missing dependencies - ConnectionFactory, JMX etc. 
Any suggestion?
In case required, I can provide the output as well. (Also, when running with `torquebox run -b 10.x.x.x`, it works fine)
